# coding: utf-8
s = slice("2014-01-01","2014-03-01")
plt.ion()
plt.plot(dftr.v_max[s], 'o')
plt.plot(dftr.v_max[s], 'o:')
plt.plot(df.v_max[s], 'o:')
df
plt.plot(dft.v_max[s], 'o:')
plt.subplots(4, sharex=True)
fig , ax= plt.subplots(4, sharex=True)
ax[0].plot(dftr.v_max[s], 'o:', label="dftr.v_max")
ax[1].plot(dftr.v[s], 'o:', label="dftr.v")
ax[2].plot(dft.v_max[s], 'o:', label="dft.v_max")
ax[3].plot(dft.v[s], 'o:', label="dft.v")
for i in range(4): ax[i].set_legend()
for i in range(4): ax[i].legend()
for i in range(4): ax[i].set_ylim(-5, 70)
pd.max
get_ipython().magic('time x =  df["v","v_max"].max(axis=1)')
get_ipython().magic('pinfo df.max')
get_ipython().magic('time x = df[["v","v_max"]].max(axis=1)')
x
get_ipython().magic('pinfo df.drop')
df.drop("v_max", axis=1, inplace=True)
get_ipython().magic('save huiiii.py 1050')
get_ipython().magic('save huiiii.py 1-50')
